<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!-- DTD tag -->
<!DOCTYPE menuInfo
[
  <!ELEMENT menuInfo (title, summary, effective-Date, menu+)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT summary (#PCDATA)>
  <!ELEMENT effective-Date (#PCDATA)>
  <!ELEMENT menu (category, menuItem+)>
  <!ELEMENT category (#PCDATA)>
  <!ELEMENT menuItem (itemName, description, price, indicator*)>
  <!ELEMENT itemName (originalName, oldName?)>
  <!ELEMENT originalName (#PCDATA)>
  <!ELEMENT oldName (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT indicator (#PCDATA)>
]>
<menuInfo>
  <title>Chester's Breakfast Menu</title>
  <summary>
@@ -8,7 +26,7 @@
    up just the way you like them!!
    ]]>
  </summary>
  <effective Date>03/12/2016</effective Date>
  <effective-Date>03/12/2016</effective-Date>
  <menu>
    <category>Traditional Favorites</category>
    <menuItem>
@@ -28,7 +46,7 @@
    </menuItem>
    <menuItem>
      <itemName>
        <originalName> Fresh Mornin' Sampler </originalname>
        <originalName> Fresh Mornin' Sampler </originalName>
        <oldName> Mornin' Sampler </oldName>
      </itemName>
      <description>
@@ -48,7 +66,7 @@
    <category>Lite and Quick</category>
    <menuItem>
      <itemName>
        <name> Oatmeal Breakfast </originalName>
        <originalName> Oatmeal Breakfast </originalName>
      </itemName>
      <description>
        <![CDATA[
@@ -79,4 +97,8 @@
      <indicator>&#9832;</indicator>  <!-- Low-carb -->
    </menuItem>
  </menu>
</menuInfo>
</menuInfo>
<!-- 
  name : Heli Kheni
  student nu : N01530895 
-->